config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_dropdown.html.erb
<%= link_to 'About', page_path('about'), class: 'dropdown-item' %>
<% if user_signed_in? %>
<%= link_to 'Edit account', edit_user_registration_path, class: 'dropdown-item' %>
<%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'dropdown-item' %>
<% else %>
<%= link_to 'Sign in', new_user_session_path, class: 'dropdown-item' %>
<%= link_to 'Sign up', new_user_registration_path, class: 'dropdown-item' %>
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>   <%= link_to "Didn't get the email?", new_confirmation_path(resource_name), class: 'dropdown-item' %>
<% end -%></li>
<% end %>
<% if user_signed_in? %>
<%= link_to 'Users', users_path, class: 'dropdown-item' %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link dropdown-item' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link dropdown-item' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link dropdown-item' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link dropdown-item' %></li>
  <li class='nav-item'> <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>   <%= link_to "Didn't get the email?", new_confirmation_path(resource_name), class: 'nav-link dropdown-item' %>
<% end -%></li>
<% end %>
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link dropdown-item' %></li>
  <li class='nav-item'><a href=" nav-link" title=""></a></li>
<% end %>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-md navbar-dark bg-dark flex-row">
        <div  class="nav-item float-left"><a href="/" title=""><%= image_tag("favicon.PNG", height: '22', width: '22') %></a></div>
        <a class="navbar-brand mr-auto" href="/">
            <%= link_to 'Hudson Lab', root_path, class: 'navbar-brand' %>
        </a>
        <ul class="navbar-nav flex-row mr-lg-0 ">

            <li class="nav-item">

                 <a class="nav-link pr-2"><i class="fa fa-search"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link pr-2"><i class="fa fa-facebook"></i></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle mr-3 mr-lg-0" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i><span class="caret"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right   " aria-labelledby="navbarDropdownMenuLink">
                   <ul>

                   </ul><%= render 'layouts/dropdown' %>

                </div>
            </li>
        </ul>
        <button class="navbar-toggler ml-lg-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <nav class="navbar navbar-expand-md navbar-light">
        <div class="collapse navbar-collapse ml-4" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto pc-menu ml-4 ">
                 <%= render 'layouts/navigation_links' %>
                 <%= render 'layouts/nav_links_for_auth' %>



            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2 bg-inverse rounded-0" type="text" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0 rounded-0" id="top-serch" type="submit">Search</button>
            </form>
        </div>
    </nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link mobile-menu' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hudsonlab" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hudsonlab" %>">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
     <link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  </head>
  <body>
    <% if user_signed_in? %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
<%end%>
       <%= render 'layouts/messages' %>
       <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>